[package]
name = "harfbuzz_fontations"
edition = "2021"

[dependencies]
read-fonts = "0.27.2"
skrifa = "0.28.1"

[lib]
name = "harfbuzz_fontations"
path = "lib.rs"
crate-type = ["staticlib"]

[profile.debugoptimized]
inherits = "release"
debug = true
