name: configs-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: install dependencies
      run: sudo apt-get install gcc
    - name: HB_DISABLE_DEPRECATED
      run: g++ -std=c++11 -c src/harfbuzz.cc -DHB_DISABLE_DEPRECATED
    - name: HB_MINI
      run: g++ -std=c++11 -c src/harfbuzz.cc -DHB_MINI
    - name: HB_LEAN
      run: g++ -std=c++11 -c src/harfbuzz.cc -DHB_LEAN
    - name: HB_TINY
      run: g++ -std=c++11 -c src/harfbuzz.cc -DHB_TINY
