name: macos-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: Install Dependencies
      run: |
        export HOMEBREW_NO_AUTO_UPDATE=1
        export HOMEBREW_NO_INSTALL_CLEANUP=1
        brew install \
          cairo \
          freetype \
          glib \
          glib-utils \
          gobject-introspection \
          graphite2 \
          gtk-doc \
          icu4c \
          meson \
          ninja \
          pkg-config
    - name: Install Python Dependencies
      run: pip3 install fonttools
    - name: Setup Meson
      run: |
        export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig"
        ccache --version
        meson setup build \
          -Dauto_features=enabled \
          -Dchafa=disabled \
          -Dcoretext=enabled \
          -Dgraphite=enabled \
          -Doptimization=2
    - name: Build
      run: meson compile -Cbuild
    - name: Test
      run: meson test --print-errorlogs -Cbuild
